site_name: USTC 程序语言设计与程序分析 2026
repo_name: ustc-pldpa/pldpa2026
repo_url: https://github.com/ustc-pldpa/pldpa2026/
theme:
  name: 'material'
  palette:
    primary: 'black'
  language: 'zh'
  features:
    - content.code.copy
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - mdx_spanner # Markdown Table Merge Cells. See https://pypi.org/project/mdx-spanner/
  - admonition  # extension for !!! note. See https://python-markdown.github.io/extensions/admonition/
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - pymdownx.details
  - mdx_truly_sane_lists
  - pymdownx.caret # for mark, ins and del HTML tags
  - pymdownx.mark  # for mark, ins and del HTML tags
  - pymdownx.tilde # for mark, ins and del HTML tags
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css # css for emoji/icon color, see https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-colors
nav:
  - 首页: index.html
  # - 课程安排: schedule.md
  # - 公共文档:
  #   - C++ 介绍: common/simple_cpp.md
  #   - IDE 配置: common/ide.md
  #   - 平台介绍:
  #     - 头歌平台: common/educoder.md
  # - 拓展阅读:
  #   - 词法分析:
  #     - 从词法分析到LLM Tokenizer: further/tokenizer.md
  #   - 其他: further/further.md
